# Generated by Django 4.0.4 on 2022-05-25 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useremail_alter_user_email_user_user_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_emails',
        ),
        migrations.AddField(
            model_name='useremail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
