# Generated by Django 4.0.4 on 2022-05-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
