# Generated by Django 4.0.4 on 2022-05-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_number_of_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_block_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
