# Generated by Django 4.0.4 on 2022-05-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_otp_block_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
